include:
  - services/docker-compose.yaml

services:

  # Content DB Migration
  content-db-migration:
    build:
      context: .
      labels:
        - ghcr.io/sowers-io/bosca/content-db-migration:dev
      dockerfile: Dockerfile-migration
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=content
    environment:
      GOOSE_DBSTRING: "user=bosca password=bosca host=postgres dbname=boscacontent"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net1

  # Profiles DB Migration
  profiles-db-migration:
    build:
      context: .
      dockerfile: Dockerfile-migration
      labels:
        - ghcr.io/sowers-io/bosca/profiles-db-migration:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=profiles
    environment:
      GOOSE_DBSTRING: "user=bosca password=bosca host=postgres dbname=boscaprofiles"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net1

  # Security DB Migration
  security-db-migration:
    build:
      context: .
      dockerfile: Dockerfile-migration
      labels:
        - ghcr.io/sowers-io/bosca/security-db-migration:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=security
    environment:
      GOOSE_DBSTRING: "user=bosca password=bosca host=postgres dbname=boscasecurity"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net1

  # Profiles gRPC Service
  profiles:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/profiles:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=profiles
        - GRPC_PORT=5004
        - REST_PORT=5014
    env_file:
      - .env-dev
    ports:
      - "5004:5004"
      - "5014:5014"
    depends_on:
      - profiles-db-migration
      - spicedb
    networks:
      - net1

  # Content gRPC Service
  content:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/content:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=content
        - GRPC_PORT=5003
        - REST_PORT=5013
    env_file:
      - .env-dev
    ports:
      - "5003:5003"
      - "5013:5013"
    depends_on:
      content-db-migration:
        condition: service_completed_successfully
      temporal:
        condition: service_healthy
      minio-nginx:
        condition: service_healthy
      spicedb:
        condition: service_healthy
    networks:
      - net1

  # Search gRPC Service
  search:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/search:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=search
        - GRPC_PORT=5005
        - REST_PORT=5015
    env_file:
      - .env-dev
    ports:
      - "5005:5005"
      - "5015:5015"
    depends_on:
      - meilisearch
      - qdrant
      - ollama
      - spicedb
    networks:
      - net1

  # AI gRPC Service
  ai:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-llamaindex
      labels:
        - ghcr.io/sowers-io/bosca/ai:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=api/ai.py
        - GRPC_PORT=5007
        - REST_PORT=5017
    env_file:
      - .env-dev
    ports:
      - "5007:5007"
      - "5017:5017"
    depends_on:
      - meilisearch
      - qdrant
      - ollama
      - spicedb
    networks:
      - net1

  # AI Vectorizer Worker
  ai-vectorizer:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-llamaindex
      labels:
        - ghcr.io/sowers-io/bosca/ai-vectorizer:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=workers/vectorizer/main.py
        - GRPC_PORT=5107
        - REST_PORT=5117
    env_file:
      - .env-dev
    ports:
      - "5107:5107"
      - "5117:5117"
    depends_on:
      - qdrant
      - ollama
    networks:
      - net1

  # Security gRPC Service
  security:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/security:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=security
        - GRPC_PORT=5006
        - REST_PORT=5016
    env_file:
      - .env-dev
    ports:
      - "5006:5006"
      - "5016:5016"
    depends_on:
      - security-db-migration
      - spicedb
    networks:
      - net1

  # Uploader HTTP Server
  uploader:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/uploader:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=uploader
        - REST_PORT=8099
    env_file:
      - .env-dev
      - .env-uploader-dev
    ports:
      - "8099:8099"
    depends_on:
      - content
      - minio-nginx
    networks:
      - net1

  # Metadata Worker
  metadata-worker:
    restart: always
    build:
      context: .
      labels:
        - ghcr.io/sowers-io/bosca/workers/workflow:dev
      dockerfile: Dockerfile-backend-core
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=workers/metadata
    env_file:
      - .env-dev
    depends_on:
      - temporal
      - meilisearch
      - qdrant
      - ollama
      - spicedb
    networks:
      - net1

  # Text Extractor Worker
  textextractor-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/workers/textextractor:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=workers/textextractor
    env_file:
      - .env-dev
    depends_on:
      temporal:
        condition: service_healthy
      textextractor:
        condition: service_healthy
    networks:
      - net1

  # Bible Worker
  bible-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-backend-core
      labels:
        - ghcr.io/sowers-io/bosca/workers/bible:dev
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        - BACKEND=workers/bible
    env_file:
      - .env-dev
    depends_on:
      temporal:
        condition: service_healthy
      textextractor:
        condition: service_healthy
    networks:
      - net1