[tool.poetry]
name = "bosca"
version = "0.1.0"
description = ""
authors = ["Kyle Brock <kyle@sowers.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
