apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb
  namespace: spicedb
spec:
  config:
    datastoreEngine: postgres
    channel: stable
    version: v1.31.0
    replicas: 2
    pgbouncer: "true"
  secretName: spicedb