apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.2-0
  postgresVersion: 16
  instances:
    - name: db1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: postgres-ha
                    postgres-operator.crunchydata.com/instance-set: db1
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostssl all all all md5"
          - "hostnossl all all all md5"
  users:
    - name: postgres
      databases:
        - postgres
      options: 'SUPERUSER'
    - name: spicedb
      databases:
        - spicedb
      options: 'LOGIN'
    - name: boscaaccounts
      databases:
        - boscaaccounts
      options: 'LOGIN'
    - name: boscaprofiles
      databases:
        - boscaprofiles
      options: 'LOGIN'
    - name: boscacontent
      databases:
        - boscacontent
      options: 'LOGIN'
    - name: boscasecurity
      databases:
        - boscasecurity
      options: 'LOGIN'
    - name: kong
      databases:
        - kong
      options: 'LOGIN'
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 5Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.21-3
      replicas: 2
      config:
        global:
          client_tls_sslmode: allow
          default_pool_size: "100"
          max_client_conn: "500"
          pool_mode: session
          query_wait_timeout: "240"
          ignore_startup_parameters: plan_cache_mode,extra_float_digits
          # server_tls_sslmode: disable
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: postgres-ha
                    postgres-operator.crunchydata.com/role: pgbouncer