x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-04-06T05-26-02Z
  command: server --console-address ":9011" http://minio{1...4}/data{1...2}
  expose:
    - "9010"
    - "9011"
  healthcheck:
    test: [ "CMD", "mc", "ready", "local" ]
    interval: 5s
    timeout: 5s
    retries: 5
  environment:
    - MINIO_ACCESS_KEY=67fO5gFs6BuksBrh6rMp
    - MINIO_SECRET_KEY=eV4rlwomvXsM19CXorOTb5uYaFLeNXsPLKx5Uxdm
  networks:
    - net1

services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=bosca
      - POSTGRES_USER=bosca
      - POSTGRES_DB=bosca
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bosca"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - net1

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    command:
      - migrate
      - sql
      - --yes
      - "postgres://bosca:bosca@postgres:5432/hydra?sslmode=disable"
    environment:
      SECRETS_SYSTEM: J6HsjnqeGHqVai7GVlFbKQi6Je189fMF
      DSN: "postgres://bosca:bosca@postgres:5432/hydra?sslmode=disable"
    networks:
      - net1
    depends_on:
      - postgres

  kratos-migrate:
    image: oryd/kratos:v1.1.0
    command:
      - migrate
      - sql
      - --yes
      - "postgres://bosca:bosca@postgres:5432/kratos?sslmode=disable"
    environment:
      SECRETS_SYSTEM: J6HsjnqeGHqVai7GVlFbKQi6Je189fMF
      DSN: "postgres://bosca:bosca@postgres:5432/kratos?sslmode=disable"
    networks:
      - net1
    depends_on:
      - postgres

  hydra:
    image: oryd/hydra:v2.2.0
    command:
      - serve
      - all
      - --config
      - /etc/hydra/config/hydra.yaml
    ports:
      - '4444:4444'
      - '4445:4445'
    volumes:
      - ./hydra:/etc/hydra/config
    environment:
      SECRETS_SYSTEM: J6HsjnqeGHqVai7GVlFbKQi6Je189fMF
      DSN: "postgres://bosca:bosca@postgres:5432/hydra?sslmode=disable"
    networks:
      - net1
    depends_on:
      - hydra-migrate

  kratos:
    image: oryd/kratos:v1.1.0
    command:
      - serve
      - all
      - --config
      - /etc/kratos/config/kratos.yaml
    ports:
      - '4433:4433'
      - '4434:4434'
    volumes:
      - ./kratos:/etc/kratos/config
    environment:
      SECRETS_SYSTEM: J6HsjnqeGHqVai7GVlFbKQi6Je189fMF
      COURIER_SMTP_CONNECTION_URI: "smtp://mailhog:1025"
      DSN: "postgres://bosca:bosca@postgres:5432/kratos?sslmode=disable"
    networks:
      - net1
    depends_on:
      - kratos-migrate

  spicedb:
    image: authzed/spicedb:v1.31.0
    command: "serve"
    restart: "always"
    ports:
      - "8080:8080"
      - "9093:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=bosca-spicedb"
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://bosca:bosca@postgres:5432/spicedb?sslmode=disable"
    depends_on:
      - spicedb-migrate
    networks:
      - net1

  spicedb-schema:
    image: authzed/zed:v0.18.0
    command:
      - schema
      - write
      - /tmp/schema
      - --insecure
      - --endpoint
      - spicedb:50051
      - --token
      - bosca-spicedb
    volumes:
      - ./spicedb/schema:/tmp/schema:ro
    restart: on-failure:100000
    depends_on:
      - spicedb
    networks:
      - net1

  spicedb-migrate:
    image: authzed/spicedb:v1.31.0
    command: "migrate head"
    restart: "on-failure"
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://bosca:bosca@postgres:5432/spicedb?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - net1

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - minio-data1-1:/data1
      - minio-data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - minio-data2-1:/data1
      - minio-data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - minio-data3-1:/data1
      - minio-data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - minio-data4-1:/data1
      - minio-data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9010:9010"
      - "9011:9011"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - net1

  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '9080:8080'
      - '7077:7077'
    networks:
      - net1

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '9081:8081'
    networks:
      - net1

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.23.1
    networks:
      - net1
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.26.2
    networks:
      - net1
    ports:
      - 8085:8080

  temporal:
    depends_on:
      - postgres
    environment:
      - DB=postgres
      - DB_PORT=5432
      - POSTGRES_USER=bosca
      - POSTGRES_PWD=bosca
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.23.1
    networks:
      - net1
    ports:
      - 7233:7233
    volumes:
      - ./temporal:/etc/temporal/config/dynamicconfig

  mlflow:
    restart: always
    image: ghcr.io/mlflow/mlflow:v2.0.1
    depends_on:
      - postgres
    ports:
      - "5001:5000"
    networks:
      - net1
    environment:
      - AWS_ACCESS_KEY_ID=67fO5gFs6BuksBrh6rMp
      - AWS_SECRET_ACCESS_KEY=eV4rlwomvXsM19CXorOTb5uYaFLeNXsPLKx5Uxdm
      - MLFLOW_S3_ENDPOINT_URL=http://nginx:9010
      - MLFLOW_S3_IGNORE_TLS=true
    command:
      - bash
      - -c
      - "python3 -m pip install pip --upgrade && \ python3 -m pip install psycopg2-binary && \ mlflow server --backend-store-uri postgresql://bosca:bosca@postgres:5432/mlflow --host 0.0.0.0 --serve-artifacts --artifacts-destination s3://mlflow"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    tty: true
    restart: always
    networks:
      - net1

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama
    ports:
      - 8086:8080
    environment:
      - '/ollama/api=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - net1

  text-extractor:
    image: ghcr.io/sowers-io/bosca/text-extractor:93732fe8eafc7ea35fed329c76a2424c8a04445e
    ports:
      - 8083:8080
    networks:
      - net1

networks:
  net1:

volumes:
  postgres:
  postgresjobqueue:
  minio-data1-1:
  minio-data1-2:
  minio-data2-1:
  minio-data2-2:
  minio-data3-1:
  minio-data3-2:
  minio-data4-1:
  minio-data4-2: