---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: bosca
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: content
        image: ghcr.io/sowers-io/bosca/content:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /alive
            port: 5003
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 5003
          - containerPort: 5013
        env:
          - name: BOSCA_ACCOUNTS_API_SERVICE_USERNAME
            valueFrom:
              secretKeyRef:
                name: service-credentials
                key: username
          - name: BOSCA_ACCOUNTS_API_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-credentials
                key: password
          - name: BOSCA_CERTIFICATE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-credentials
                key: certificate-password
          - name: BOSCA_CONTENT_DB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: content-database-credentials
                key: content-connection
        envFrom:
        - configMapRef:
            name: content-env
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: packages-credentials