---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  namespace: bosca
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: mail
        image: ghcr.io/sowers-io/bosca/mail:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /alive
            port: 5002
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 5002
          - containerPort: 5012
        env:
          - name: BOSCA_ACCOUNTS_API_SERVICE_USERNAME
            valueFrom:
              secretKeyRef:
                name: service-credentials
                key: username
          - name: BOSCA_ACCOUNTS_API_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-credentials
                key: password
          - name: BOSCA_CERTIFICATE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-credentials
                key: certificate-password
        envFrom:
        - configMapRef:
            name: mail-env
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: packages-credentials