---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: bosca
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: ghcr.io/sowers-io/bosca/graphql:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: graphql-env
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: packages-credentials