name: GO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: bosca
          POSTGRES_USER: bosca
          POSTGRES_DB: bosca
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Initialize CI
        run: ./scripts/initialize
      - name: Build Go
        run: ./scripts/build-go
      - name: Test
        run: ./scripts/test
      - name: Build Docker
        run: ./scripts/build-docker
      - name: Publish
        run: ./scripts/publish-docker
